#!/usr/bin/env node
/**
 * checkpoint.mjs — Project State Engine (ADR-001).
 *
 * Zero-dependency, plain ESM Node script so it runs identically on the dev
 * machine, in CI, and inside any fresh sandbox — no build step, no npm deps.
 *
 * Usage:
 *   node scripts/checkpoint.mjs status
 *   node scripts/checkpoint.mjs complete "P0-T1: ..."
 *   node scripts/checkpoint.mjs plan "P1-T2: ..."
 *   node scripts/checkpoint.mjs decide "ADR-001: State engine" "reasoning..."
 *   node scripts/checkpoint.mjs phase phase-1-expert-tree
 *   node scripts/checkpoint.mjs sync             # rebuild HANDOFF.md + commit if dirty
 *
 * The command set is intentionally tiny; agents and humans both use it.
 * Everything it writes is idempotent and safe to re-run.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const STATE_PATH = join(ROOT, 'scripts', 'agent_state.json');
const HANDOFF_PATH = join(ROOT, 'docs', 'HANDOFF.md');

export function loadState(path = STATE_PATH) {
  if (!existsSync(path)) {
    throw new Error(`State file missing: ${path}. This repo is corrupt — restore from git.`);
  }
  return JSON.parse(readFileSync(path, 'utf8'));
}

export function saveState(state, path = STATE_PATH) {
  state.updated_at = new Date().toISOString();
  state.last_checkpoint = state.updated_at;
  state.update_count = (state.update_count ?? 0) + 1;
  writeFileSync(path, JSON.stringify(state, null, 2) + '\n');
  return state;
}

function completeTask(state, task) {
  state.pending_tasks = state.pending_tasks.filter((t) => t !== task);
  if (!state.completed_tasks.includes(task)) {
    state.completed_tasks.push({ task, at: new Date().toISOString() });
  }
}

function planTask(state, task) {
  if (state.pending_tasks.includes(task)) return;
  if (state.completed_tasks.some((c) => c.task === task)) return;
  state.pending_tasks.push(task);
}

function decide(state, id, reasoning) {
  if (state.architectural_decisions.some((d) => d.id === id)) return;
  state.architectural_decisions.push({ id, reasoning, at: new Date().toISOString() });
}

export function renderHandoff(state) {
  const lines = [];
  lines.push('# HANDOFF — read this FIRST when resuming work');
  lines.push('');
  lines.push('> Auto-regenerated by `node scripts/checkpoint.mjs sync`. Do not edit by hand.');
  lines.push('');
  lines.push('## Where we are');
  lines.push('');
  lines.push(`- **Phase:** ${state.current_phase} — ${state.phases[state.current_phase]?.name ?? ''}`);
  lines.push(`- **Last checkpoint:** ${state.last_checkpoint}`);
  lines.push(`- **Git:** run \`git log --oneline -3\` to see the last commits.`);
  lines.push('');
  lines.push('## Protocol (non-negotiable)');
  lines.push('');
  lines.push('1. Read `scripts/agent_state.json` (the brain).');
  lines.push('2. Read `docs/ROADMAP.md` for the current phase tasks.');
  lines.push('3. Do the work. Run tests. Keep SPEC.md honest.');
  lines.push('4. `node scripts/checkpoint.mjs complete "<task>"` after each task.');
  lines.push('5. `node scripts/checkpoint.mjs sync` — this rewrites this file and commits.');
  lines.push('');
  lines.push('## Pending (in order)');
  lines.push('');
  for (const t of state.pending_tasks) lines.push(`- [ ] ${t}`);
  lines.push('');
  lines.push('## Completed');
  lines.push('');
  const recent = state.completed_tasks.slice(-15);
  for (const c of recent) lines.push(`- [x] ${c.task} (${c.at.slice(0, 10)})`);
  lines.push('');
  lines.push('## Architectural decisions');
  lines.push('');
  for (const d of state.architectural_decisions) {
    lines.push(`- **${d.id}** — ${d.reasoning}`);
  }
  lines.push('');
  return lines.join('\n');
}

function git(args) {
  try {
    return execSync(`git ${args}`, { cwd: ROOT, stdio: ['ignore', 'pipe', 'pipe'] })
      .toString()
      .trim();
  } catch {
    return '';
  }
}

function syncAndCommit() {
  const state = loadState();
  writeFileSync(HANDOFF_PATH, renderHandoff(state));
  const branch = git('rev-parse --abbrev-ref HEAD');
  const dirty = git('status --porcelain');
  if (!dirty) {
    console.log(`checkpoint: clean working tree on ${branch}, nothing to commit.`);
    return false;
  }
  git('add -A');
  const phase = state.current_phase;
  const msg = `chore(state): checkpoint ${phase} — ${state.completed_tasks.length} done, ${state.pending_tasks.length} pending [skip ci]`;
  execSync(`git commit -m ${JSON.stringify(msg)}`, { cwd: ROOT, stdio: 'inherit' });
  console.log(`checkpoint: committed on ${branch}`);
  return true;
}

// --- CLI ---
const [, , cmd, ...args] = process.argv;
switch (cmd) {
  case 'status':
    console.log(JSON.stringify(loadState(), null, 2));
    break;
  case 'complete': {
    const s = loadState();
    completeTask(s, args.join(' '));
    saveState(s);
    writeFileSync(HANDOFF_PATH, renderHandoff(s));
    break;
  }
  case 'plan': {
    const s = loadState();
    planTask(s, args.join(' '));
    saveState(s);
    writeFileSync(HANDOFF_PATH, renderHandoff(s));
    break;
  }
  case 'decide': {
    const s = loadState();
    decide(s, args[0], args.slice(1).join(' '));
    saveState(s);
    writeFileSync(HANDOFF_PATH, renderHandoff(s));
    break;
  }
  case 'phase': {
    const s = loadState();
    if (!s.phases[args[0]]) throw new Error(`unknown phase: ${args[0]}`);
    if (s.phases[s.current_phase]) s.phases[s.current_phase].status = 'done';
    s.current_phase = args[0];
    s.phases[args[0]].status = 'in_progress';
    saveState(s);
    writeFileSync(HANDOFF_PATH, renderHandoff(s));
    break;
  }
  case 'sync':
    syncAndCommit();
    break;
  default:
    console.error('usage: checkpoint.mjs status|complete|plan|decide|phase|sync');
    process.exit(cmd ? 1 : 0);
}
